CREATE TABLE IF NOT EXISTS `dz_skill` (
    `id` int(10) NOT NULL AUTO_INCREMENT,
    `user_id` int(30) NOT NULL DEFAULT 0,
    `mechanic_lvl` int(30) NOT NULL DEFAULT 1,
    `mechanic_exp` int(30) NOT NULL DEFAULT 1,
    `steal_lvl` int(30) NOT NULL DEFAULT 1,
    `steal_exp` int(30) NOT NULL DEFAULT 1,
    `athletics_lvl` int(30) NOT NULL DEFAULT 1,
    `athletics_exp` int(30) NOT NULL DEFAULT 1,
    `swimming_lvl` int(30) NOT NULL DEFAULT 1,
    `swimming_exp` int(30) NOT NULL DEFAULT 1,
    `strenght_lvl` int(30) NOT NULL DEFAULT 1,
    `strenght_exp` int(30) NOT NULL DEFAULT 1,
    `shooter_lvl` int(30) NOT NULL DEFAULT 1,
    `shooter_exp` int(30) NOT NULL DEFAULT 1,
    `lung_lvl` int(30) NOT NULL DEFAULT 1,
    `lung_exp` int(30) NOT NULL DEFAULT 1,
    `chemistry_lvl` int(30) NOT NULL DEFAULT 1,
    `chemistry_exp` int(30) NOT NULL DEFAULT 1,
    `agriculture_lvl` int(30) NOT NULL DEFAULT 1,
    `agriculture_exp` int(30) NOT NULL DEFAULT 1,
    `metallurgy_lvl` int(30) NOT NULL DEFAULT 1,
    `metallurgy_exp` int(30) NOT NULL DEFAULT 1,
    `sewing_lvl` int(30) NOT NULL DEFAULT 1,
    `sewing_exp` int(30) NOT NULL DEFAULT 1,
    `fishing_lvl` int(30) NOT NULL DEFAULT 1,
    `fishing_exp` int(30) NOT NULL DEFAULT 1,
    `mining_lvl` int(30) NOT NULL DEFAULT 1,
    `mining_exp` int(30) NOT NULL DEFAULT 1,
    PRIMARY KEY(`id`)
)